<a href="https://colab.research.google.com/github/min02choi/Machine-Learning/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# 텐서 생성하기(스칼라, 단일, 순위0), 축 없음
rank_0_tensor = tf.constant(4)  # constant: 변수를 선언할 때 사용
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# 텐서 생성하기(벡터, 순위1), 축 1개
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
# 텐서 생성하기(행렬, 순위2), 축 2개
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype = tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
# 텐서 생성하기, 축 3개
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
# 텐서를 numpy배열로 변환(1)
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
# 텐서를 numpy배열로 변환(2)
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
# 텐서에 대한 기본 산술 - 표현법1
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print(tf.add(a, b), "\n")       # 동일한 위치에 있는 원소의 합
print(tf.multiply(a, b), "\n")  # 동일한 위치에 있는 원소의 곱
print(tf.matmul(a, b), "\n")    # 행렬의 곱

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



In [ ]:
# 텐서에 대한 기본 산술 - 표현법2
print(a + b, "\n")    # 동일한 위치에 있는 원소의 합
print(a * b, "\n")    # 동일한 위치에 있는 원소의 곱
print(a @ b, "\n")    # 행렬의 곱

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



In [ ]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

print(tf.reduce_max(c))     # 변수에서 가장 큰 값을 탐색
print(tf.math.argmax(c))    # 가장 큰 값의 인덱스 값을 찾음
print(tf.nn.softmax(c))     # 

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [ ]:
# tensor로의 변환
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

## 형상 정보

In [20]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])    # 각 축을 전부 0으로 설정

print("Type of every element: ", rank_4_tensor.dtype)   # 데이터 타입 확인

# ndim, shape(속성)는 텐서 객체를 반환하지 않음
print("Number of axes:", rank_4_tensor.ndim)      # 배열의 차원 확인            
print("Shape of tensor:", rank_4_tensor.shape)

print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element:  <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [15]:
# 텐서가 필요한 경우 tf.rank, tf.shape 함수 사용
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [16]:
tf.shape(rank_4_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>

## 인덱싱

표준 Python 인덱싱 규칙을 따름

In [29]:
# 단일 축 인덱싱
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

print(rank_1_tensor)                        # 텐서 자체를 출력
print(rank_1_tensor.numpy())                # 텐서의 값을 출력
print("First: ", rank_1_tensor[0].numpy())  # 스칼라 사용 인덱싱 -> 축 제거
print("Slice from 2, before 7: ", rank_1_tensor[2:7].numpy()) # ':' 이용 슬라이싱 -> 축 유지
print("Jump item: ", rank_1_tensor[::2].numpy())    # 인덱스 2를 간격으로 뜀
print("Reversed: ", rank_1_tensor[::-1].numpy())    # 반대로 뒤집기

tf.Tensor([ 0  1  1  2  3  5  8 13 21 34], shape=(10,), dtype=int32)
[ 0  1  1  2  3  5  8 13 21 34]
First:  0
Slice from 2, before 7:  [1 2 3 5 8]
Jump item:  [ 0  1  3  8 21]
Reversed:  [34 21 13  8  5  3  2  1  1  0]


In [73]:
# 다축 인덱싱 -> 여러 인덱스 사용, 단일 축의 경우에서와 같은 규칙이 각 축에 독립적으로 작용
print(rank_2_tensor.numpy())

print(rank_2_tensor[1, 1].numpy())    # 각 축에 정수 전잘 시 결과는 스칼라
print("Second row:", rank_2_tensor[1, :].numpy())     # 1번째 행 전부 출력
print("Second column:", rank_2_tensor[:, 1].numpy())  # 1번째 열 전부 출력
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")             # 0번째 행 제외 전부 출력(1번째 행부터 끝까지 출력)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
4.0
Second row: [3. 4.]
Second column: [2. 4. 6.]
Skip the first row:
[[3. 4.]
 [5. 6.]] 



## 형상 조작하기

In [35]:
x = tf.constant([[1], [2], [3]])
print(x.shape)
print(x.shape.as_list())    # 파이썬 배열로 반환

(3, 1)
[3, 1]


In [37]:
# 새로운 형상으로 변환하기(tf.reshape)
reshaped = tf.reshape(x, [1, 3])
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [74]:
print(rank_3_tensor)
print(tf.reshape(rank_3_tensor, [-1]))        # -1 일렬로 텐서를 나열
print(tf.reshape(rank_3_tensor, [2, 3, 5]))   # 원하는 shape대로 모양 변형

# rank_3_tensor은 현재 3*2*5 = 30임
# reshape를 할때 곱해서 도합 30이 나오게끔 shape 설정([1, 30], [2, 15], [2, 3, 5] 등)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32)


### Dtypes에 대한 추가 정보
tf.Tensor의 데이터 유형을 검사하려면, Tensor.dtype 속성을 사용<br>
Python 객체에서 tf.Tensor를 만들 때 선택적으로 데이터 유형을 지정할 수 있음
* Python 정수 -> tf.int32
* Python 부동 소수점 -> tf.float32

In [46]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64) # float64로 데이터 타입 지정
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)      # float16으로 캐스팅

# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)         # 정수형으로 변환 -> 소숫점 아래 잃게 됨
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


### 브로드캐스팅
특정 조건에서 작은 텐서는 결합된 연산을 실행할 때 더 큰 텐서에 맞게 자동으로 '확장'을 함

In [53]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])

# 아래는 다 같은 연산임
print(tf.multiply(x, 2))    # x의 각 원소에 2를 곱함
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [50]:
print(x.numpy())
x = tf.reshape(x, [3, 1])
print(x.numpy())

# 근데 궁금한 점: 어떨 때는 행렬의 곱이 되고 어떨 땐 그냥 곱하기가 됨? constant가 영향이 있는 건가

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [56]:
# 브로드캐스팅 한 값이 무엇인지 미리 확인 가능
print(tf.broadcast_to(tf.constant([1, 2, 3]), [4, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]], shape=(4, 3), dtype=int32)


## tf.convert_to_tensor
추가로 찾아보세요

## 비정형 텐서
각 축이 다양한 수요를 가진 텐서

In [61]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

# rag = tf.constant(ragged_list)        # 정규텐서로 변환 불가
rag = tf.ragged.constant(ragged_list)   # ragged 사용할 것

print(rag)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


## 문자열 텐서
tf.string은 dtype
* 문자열은 원자성이므로 Python 문자열과 같은 방식으로 인덱싱할 수 없음
* 문자열을 조작하는 함수는 tf.strings 참고

In [65]:
# 문자열 텐서
# 출력 결과에 나오는 b는 tf.string dtype이 유니코드 문자열이 아닌 바이트 문자열임을 나타냄
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)
print(scalar_string_tensor.numpy())

# tf.strings를 이용한 문자열 조작
print(tf.strings.split(scalar_string_tensor, sep=" "))  # 공백을 기준으로 분리

# 문자열로 되어있는 숫자를 숫자로 변환
# tf.string.to_number
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor(b'Gray wolf', shape=(), dtype=string)
b'Gray wolf'
tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)
tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [66]:
# 문자열을 바이트로 변환
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))  # 각 바이트로 쪼갬
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8) # 바이트로 쪼갠 후 유니코드로 변환
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


* tf.string dtype -> TensorFlow의 모든 원시 바이트 데이터에 사용
* tf.io 모듈: 이미지 디코딩, csv 구문 분석 등 데이터를 바이트로 변환하거나 바이트에서 변환하는 함수가 포함

## 희소 텐서
매우 넓은 공간에 데이터가 희소한 경우
* tf.sparse.SparseTensor 및 관련 연산을 지원하여 희소 데이터를 효율적으로 저장

In [72]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[24, 3.5],
                                       dense_shape=[5, 6])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([24.   3.5], shape=(2,), dtype=float32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64)) 

tf.Tensor(
[[24.   0.   0.   0.   0.   0. ]
 [ 0.   0.   3.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]], shape=(5, 6), dtype=float32)
